"""initial schema

Revision ID: 6ee16370c878
Revises:
Create Date: 2026-08-20 21:20:10.691976

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6ee16370c878"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
