"""desc del in conversation

Revision ID: c2535d1b8083
Revises: 45944029b102
Create Date: 2026-08-20 21:25:50.399389

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2535d1b8083"
down_revision: str | Sequence[str] | None = "45944029b102"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
