"""utc add in model

Revision ID: c53426057591
Revises: c2535d1b8083
Create Date: 2026-08-21 00:58:20.890374

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c53426057591"
down_revision: str | Sequence[str] | None = "c2535d1b8083"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
